/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all items
     * @description Retrieve a list of all items (public endpoint, no authentication required)
     */
    get: operations['getItems'];
    put?: never;
    /**
     * Create a new item
     * @description Create a new item with the provided data (requires authentication)
     */
    post: operations['createItem'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateItemRequest: {
      /**
       * @description Item name
       * @example My Item
       */
      name: string;
      /**
       * @description Item description
       * @example This is a sample item
       */
      description?: string;
    };
    ItemResponse: {
      /**
       * Format: uuid
       * @description Item ID
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description Item name
       * @example My Item
       */
      name: string;
      /**
       * @description Item description
       * @example This is a sample item
       */
      description?: string;
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example 2024-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       * @example 2024-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
    Error: {
      /**
       * @description HTTP status code
       * @example 400
       */
      statusCode: number;
      /**
       * @description Error message
       * @example Invalid input
       */
      message: string;
      /**
       * @description Error type
       * @example Bad Request
       */
      error?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getItems: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of items */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ItemResponse'][];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  createItem: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateItemRequest'];
      };
    };
    responses: {
      /** @description Item created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ItemResponse'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
}
